### ISSUE TITLE
(myNode local mempool.space) Black block errors

### ISSUE THREAD

**Issue by Amiga500** [mempool-space/mempool.space#22] opened 2020-02-11 00:59 UTC
Using mempool.space locally on mynode fullnode (docker)
Black block isn't on the left and miss info about numbers of blocks inside of it

![image](https://user-images.githubusercontent.com/16525337/74204031-deba7b00-4c71-11ea-88b0-86adc564dd75.png)

**Comment by wiz** [comment] 2020-02-11 01:13
Ah yeah, this is a common mistake, you can't increase the number of blocks in the configuration. Can you reset back to default configuration and try again? We should remove this setting @softsimon

**Comment by wiz** [comment] 2020-02-11 01:20
i.e. don't change `DEFAULT_PROJECTED_BLOCKS_AMOUNT` from 3

**Comment by wiz** [comment] 2020-02-11 01:37
<img width="1159" alt="Screen Shot 2020-02-11 at 10 36 24" src="https://user-images.githubusercontent.com/232186/74205373-6deb8100-4cba-11ea-8eee-bedacd303645.png">

**Comment by softsimon** [comment] 2020-02-11 04:23
Looks like a display bug actually. The black block should be the last block to the left.

**Comment by Amiga500** [comment] 2020-02-11 09:51
> i.e. don't change `DEFAULT_PROJECTED_BLOCKS_AMOUNT` from 3

i have check into code.. no changes made on it!

**Comment by Amiga500** [comment] 2020-02-11 09:55
> Looks like a display bug actually. The black block should be the last block to the left.

I think too.. into black block miss too the numbers of the pool of blocks.

![image](https://user-images.githubusercontent.com/16525337/74226357-b6a43980-4cbc-11ea-960c-f9fd87f152ba.png)

![image](https://user-images.githubusercontent.com/16525337/74226519-fc610200-4cbc-11ea-8708-dd7d16d81d26.png)

**Comment by rbrooklyn** [comment] 2020-02-11 21:43
Hello.

For full disclosure, myself and Amiga500 have been talking about this bug and the other one he filed on a telegram group.

I've managed to reproduce this. Specifically the final part where the proper mempool.space website will show "+x blocks", yet Amiga500's install just keeps on going by showing "2360 transactions" and then more blocks to the left of that (you can _just_ see part of the block to the left in his screenshot) until it runs out of transactions to display, instead of stopping like it should be.

This will affect Docker installations from the Dockerfile that was merged a few weeks ago (and, shamefully, I wrote, not my best work).

This issue is, as stated, the config. However, it's not as we'd expect. It is setting a value, but maybe not in the way mempoolspace wants it.

The dockerfile produces a config which looks like this:
![image](https://user-images.githubusercontent.com/11929484/74281453-63f76b80-4d16-11ea-8418-ee7f32a1ab9a.png)

However, what it actually needs is a config like this:
![image](https://user-images.githubusercontent.com/11929484/74281529-8093a380-4d16-11ea-8085-8ed461cbbf59.png)

Notice for the "DEFAULT_PROJECTED_BLOCKS_AMOUNT" There is a "3" value and then a 3 value. One with, and one without the quotes.

It seems quotes are an issue for this value, and is causing the getProjectedBlocks function in projected-blocks.ts to get confused and then "bad things" are happening.

This is odd, as quotes _appear_ to be fine on other numeric values, such as the ports and whatnot (unless the default handling for these is a little more robust and just so happen to work by pure luck alone) so I'm unsure where the fault really lies.

Should "3" be acceptable for this value and it converts to an integer? or should it always be 3 and the DockerFile needs refinement?

**Closed** 2020-02-15 04:55 UTC
