### ISSUE TITLE
(myNode docker) sometimes the display of the graph si very different from the one on the website

### ISSUE THREAD

**Issue by Amiga500** [mempool-space/mempool.space#23] opened 2020-02-11 10:04 UTC
on myNode docker, sometimes the display of the graph si very different from the one on the website.
I have a pic of yesterday night where are missing some data. I didn't take a pic of that one on website but it was very different. The blockchain was synched.. I'll add more info the next time that will happen.

![image](https://user-images.githubusercontent.com/16525337/74226876-9de85380-4cbd-11ea-9843-26ccc25c9a74.png)

**Comment by softsimon** [comment] 2020-02-11 10:33
The graph only logs the mempool fetched off your Bitcoin Core instance. If it's recently restarted it may take a while before it builds up the "full" mempool again. You can compare the "Unconfirmed transactions" on your start page with the official mempool.space site or another block explorer website to make sure this is the case.

**Comment by Amiga500** [comment] 2020-02-11 11:16
ok.. i'll do it and let you know. thx!

**Comment by rbrooklyn** [comment] 2020-02-11 21:32
Hello.

For full disclosure, myself and Amiga500 have been talking about this bug and the other one he filed on a telegram group. We've cleared up a misunderstanding that "fully synced" doesn't mean "my mempool is the same as your mempool and all mempools are the same" and that there is no consensus on the mempool.

Having said that, I've been able to reproduce this.

My node is well aware of the current state of the mempool:
![image](https://user-images.githubusercontent.com/11929484/74280776-175f6080-4d15-11ea-855a-2c36a4e81bcd.png)

And so was mempoolspace until I restarted it:
![image](https://user-images.githubusercontent.com/11929484/74280828-35c55c00-4d15-11ea-9fa4-cd738b8c5030.png)

You can see towards the right, where the mempool seems to drop off a cliff, as if a massive block has been found (obviously impossible with current rules). This was actually me restarting the docker container.

So mempoolspace has been restarted, but Bitcoin Core has not.

It looks like what is happening here, is that mempoolspace is only seeing _new transactions from the point of it starting_, and doesn't seem to make any effort to interrogate Bitcoin Core to how it sees the mempool.

I'm unsure if this is by design or if it's considered a bug at all. I think for installations with long uptimes this isn't a major issue.

However, we're using boxes which reboot roughly once a day, so this may cause some issues for us, especially if the mempool is fairly large at the point of start-up, as this will distort our view of things. If the mempool is relatively empty then the effect will be minimal.

**Comment by rbrooklyn** [comment] 2020-02-11 21:49
Having written all of that. It looks like my node has now caught up to the mempool.space website in fairly short order.

So maybe I was making stuff up and I should have been more patient!

Left is my install catching up, right is the mempool.space website:
![image](https://user-images.githubusercontent.com/11929484/74282571-47f4c980-4d18-11ea-9b49-33047403bb1c.png)

**Comment by softsimon** [comment] 2020-02-12 10:32
It's due to restarting of the mempool.space it might take up to several minutes to get in sync with the mempool because fees needs to be recursively looked up. So before that's done it will still create some statistics entries showing mempool almost empty.

It's almost a bug because it can be improved. I have been thinking of showing a visual indicator on the website showing that it's still syncing the mempool, and it shouldn't create statistics entries if it's not caught up. :)

**Comment by Amiga500** [comment] 2020-02-12 14:50
> It's due to restarting of the mempool.space it might take up to several minutes to get in sync with the mempool because fees needs to be recursively looked up. So before that's done it will still create some statistics entries showing mempool almost empty.
> 
> It's almost a bug because it can be improved. I have been thinking of showing a visual indicator on the website showing that it's still syncing the mempool, and it shouldn't create statistics entries if it's not caught up. :)

It could be cool this solution 👍

**Comment by softsimon** [comment] 2020-02-17 05:52
Closing this issue and created a new task for a "sync process indicator" #29

**Closed by softsimon** 2020-02-17 05:52 UTC
